# Generated by Django 4.2.8 on 2025-11-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagencasa',
            name='imagen',
        ),
        migrations.AddField(
            model_name='imagencasa',
            name='imagen_data',
            field=models.BinaryField(blank=True, null=True, verbose_name='Datos de la imagen'),
        ),
        migrations.AddField(
            model_name='imagencasa',
            name='nombre_archivo',
            field=models.CharField(blank=True, help_text='Nombre original del archivo', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='imagencasa',
            name='tipo_contenido',
            field=models.CharField(blank=True, help_text='Tipo MIME (ej: image/jpeg, image/png)', max_length=100, null=True),
        ),
    ]
