# Generated by Django 4.2.8 on 2025-11-22 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_imagencasa_imagen_imagencasa_imagen_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenBase',
            fields=[
                ('id_imagen', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre descriptivo de la imagen', max_length=255)),
                ('imagen_data', models.BinaryField(verbose_name='Datos de la imagen')),
                ('tipo_contenido', models.CharField(help_text='Tipo MIME (ej: image/jpeg, image/png)', max_length=100)),
                ('categoria', models.CharField(blank=True, help_text='Categoría (ej: exterior, interior, jardín)', max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Imagen de Galería',
                'verbose_name_plural': 'Imágenes de Galería',
                'ordering': ['nombre'],
            },
        ),
        migrations.RenameField(
            model_name='imagencasa',
            old_name='id_imagen',
            new_name='id_imagen_casa',
        ),
        migrations.RemoveField(
            model_name='imagencasa',
            name='imagen_data',
        ),
        migrations.RemoveField(
            model_name='imagencasa',
            name='nombre_archivo',
        ),
        migrations.RemoveField(
            model_name='imagencasa',
            name='tipo_contenido',
        ),
        migrations.AddField(
            model_name='imagencasa',
            name='imagen_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.imagenbase', verbose_name='Imagen de la galería'),
        ),
    ]
